package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	defaultSyntheticEndpoint   = "https://api.synthetic.new/openai/v1/models"
	defaultOutput              = "synthetic_models_generated.go"
	defaultFetchTimeoutSeconds = 15
)

type syntheticModelsResponse struct {
	Data []syntheticModel `json:"data"`
}

type syntheticModel struct {
	ID                string           `json:"id"`
	Name              string           `json:"name"`
	ContextLength     int64            `json:"context_length"`
	MaxOutputLength   int64            `json:"max_output_length"`
	InputModalities   []string         `json:"input_modalities"`
	OutputModalities  []string         `json:"output_modalities"`
	SupportedFeatures []string         `json:"supported_features"`
	Pricing           syntheticPricing `json:"pricing"`
	Provider          string           `json:"provider"`
}

type syntheticPricing struct {
	Completion      string `json:"completion"`
	Prompt          string `json:"prompt"`
	InputCacheReads string `json:"input_cache_reads"`
}

func main() {
	if err := run(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "synthetic-models-gen: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	endpoint := flag.String("endpoint", defaultSyntheticEndpoint, "Synthetic models endpoint")
	output := flag.String("output", defaultOutput, "generated Go file path")
	timeout := flag.Int("timeout-seconds", defaultFetchTimeoutSeconds, "HTTP fetch timeout in seconds")
	flag.Parse()

	client := &http.Client{Timeout: time.Duration(*timeout) * time.Second}

	models, err := fetchSyntheticModels(client, *endpoint)
	if err != nil {
		return err
	}

	if len(models) == 0 {
		return fmt.Errorf("no models available from synthetic endpoint")
	}

	formatted, err := render(models)
	if err != nil {
		return err
	}

	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated file: %w", err)
	}
	return nil
}

func fetchSyntheticModels(client *http.Client, endpoint string) ([]syntheticModel, error) {
	req, err := http.NewRequest(http.MethodGet, endpoint, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("request %s: %w", endpoint, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		body, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		return nil, fmt.Errorf("%s returned %s: %s", endpoint, resp.Status, strings.TrimSpace(string(body)))
	}

	var parsed syntheticModelsResponse
	if err := json.NewDecoder(resp.Body).Decode(&parsed); err != nil {
		return nil, fmt.Errorf("decode response from %s: %w", endpoint, err)
	}

	// Filter only synthetic provider models
	syntheticModels := make([]syntheticModel, 0, len(parsed.Data))
	syntheticModels = append(syntheticModels, parsed.Data...)
	return syntheticModels, nil
}

func hasFeature(features []string, feature string) bool {
	for _, f := range features {
		if strings.EqualFold(strings.TrimSpace(f), feature) {
			return true
		}
	}
	return false
}

func hasImageModality(modalities []string) bool {
	for _, m := range modalities {
		if strings.EqualFold(strings.TrimSpace(m), "image") {
			return true
		}
	}
	return false
}

func parsePrice(priceStr string) float64 {
	priceStr = strings.TrimSpace(priceStr)
	if priceStr == "" || priceStr == "0" {
		return 0
	}
	// Remove $ prefix if present
	priceStr = strings.TrimPrefix(priceStr, "$")
	// Parse as float64 (price is per token, multiply by 1M for our format)
	val, err := strconv.ParseFloat(priceStr, 64)
	if err != nil {
		return 0
	}
	// The API returns per-token pricing, convert to per-1M
	return val * 1_000_000
}

func normalizeModel(model syntheticModel) (syntheticModel, bool) {
	model.ID = strings.TrimSpace(model.ID)
	if model.ID == "" {
		return syntheticModel{}, false
	}

	model.Name = strings.TrimSpace(model.Name)
	if model.Name == "" {
		model.Name = model.ID
	}

	if model.ContextLength <= 0 {
		model.ContextLength = 200000
	}

	if model.MaxOutputLength <= 0 {
		model.MaxOutputLength = 16384
	}

	return model, true
}

func render(models []syntheticModel) ([]byte, error) {
	// Normalize and sort models
	normalized := make([]syntheticModel, 0, len(models))
	for _, model := range models {
		if m, ok := normalizeModel(model); ok {
			normalized = append(normalized, m)
		}
	}

	sort.Slice(normalized, func(i, j int) bool {
		return normalized[i].ID < normalized[j].ID
	})

	var out bytes.Buffer
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	out.WriteString("package libagent\n\n")
	out.WriteString("var syntheticGeneratedModels = []ModelInfo{\n")
	for _, model := range normalized {
		writeModelLiteral(&out, model)
	}
	out.WriteString("}\n")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

func writeModelLiteral(out *bytes.Buffer, model syntheticModel) {
	canReason := hasFeature(model.SupportedFeatures, "reasoning")
	supportsImages := hasImageModality(model.InputModalities)
	costPer1MIn := parsePrice(model.Pricing.Prompt)
	costPer1MOut := parsePrice(model.Pricing.Completion)

	_, _ = fmt.Fprintf(out, "\t{\n")
	_, _ = fmt.Fprintf(out, "\t\tProviderID:       SyntheticProviderID,\n")
	_, _ = fmt.Fprintf(out, "\t\tModelID:          %q,\n", model.ID)
	_, _ = fmt.Fprintf(out, "\t\tName:             %q,\n", model.Name)
	_, _ = fmt.Fprintf(out, "\t\tContextWindow:    %d,\n", model.ContextLength)
	_, _ = fmt.Fprintf(out, "\t\tDefaultMaxTokens: %d,\n", model.MaxOutputLength)
	if canReason {
		_, _ = fmt.Fprintf(out, "\t\tCanReason:        true,\n")
	}
	if supportsImages {
		_, _ = fmt.Fprintf(out, "\t\tSupportsImages:   true,\n")
	}
	if costPer1MIn != 0 {
		_, _ = fmt.Fprintf(out, "\t\tCostPer1MIn:      %s,\n", formatFloat(costPer1MIn))
	}
	if costPer1MOut != 0 {
		_, _ = fmt.Fprintf(out, "\t\tCostPer1MOut:     %s,\n", formatFloat(costPer1MOut))
	}
	_, _ = fmt.Fprintf(out, "\t},\n")
}

func formatFloat(value float64) string {
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%.6f", value), "0"), ".")
}
